// Add Element to the Box

let p = document.createElement('span');
p.textContent = "My name is Paragraph and I am generated by Js";
let box = document.querySelector(".box");
// box.appendChild(p)

// InsertBefore
let ankit = document.querySelector("#ankit");
 
// box.insertBefore(p,ankit)

// RemoveChild
// box.removeChild(ankit)
document.write("Hey")
document.write("Hey 1")
document.write("Hey 2")
console.log(document.location);
 

// TextContent and Styling Using Js
let btn = document.querySelector("button")
btn.addEventListener("click",()=>{
    box.style.backgroundColor = "orange";
    box.innerText += "Button is Clicked"
})
